### ISSUE TITLE
博客字体感觉有点小啊

### ISSUE THREAD

**Issue by chuxinyuan** [shrektan/shrektan_blog#5]
个人愚见：字体比较小的情况下，人眼首先解决的是是否能看清楚的问题，所以无衬线字体可能更适合点，因为它更简洁点，看的更清楚；字体比较大的时候看清楚这个问题就不是主要矛盾了，这时候主要考虑的是审美问题。

鉴于上述原因，我认为字体大一点才能体现思源字体的美感。因此冒昧建议您的博客的字体调大一点，当然这个不是必须的，因为读者可以通过浏览器显示比例调整来达到想要的效果。

**Comment by shrektan** [comment]
感谢建议。最近打算把博客改版下，届时一并操作。

**Comment by chuxinyuan** [comment]
顺便可以整个评论功能就更棒了！
